name: unlocking-information
channels:
    - conda-forge
    - pytorch

dependencies:
    - python=3.9
    - numpy = 1.23.4
    - pip=22.3.1
    - pytorch::pytorch=1.13.1

    - pip: # use '==' here
        - altair==4.2.2
        - beautifulsoup4==4.12.2
        - blinker==1.6.2
        - boto3==1.26.114
        - botocore==1.29.114
        - cachetools==5.3.0
        - charset-normalizer==3.1.0
        - click==8.1.3
        - cloudpickle==2.2.1
        - contourpy==1.0.7
        - copulas==0.8.0
        - ctgan==0.7.1
        - cycler==0.11.0
        - decorator==5.1.1
        - deepecho==0.4.0
        - entrypoints==0.4
        - Faker==14.2.1
        - fonttools==4.39.3
        - gitdb==4.0.10
        - GitPython==3.1.31
        - idna==3.4
        - importlib-metadata==6.4.1
        - Jinja2==3.1.2
        - jmespath==1.0.1
        - joblib==1.2.0
        - jsonschema==4.17.3
        - kiwisolver==1.4.4
        - markdown-it-py==2.2.0
        - MarkupSafe==2.1.2
        - matplotlib==3.7.1
        - numpy==1.24.2
        - packaging==21.3
        - pandas==1.5.3
        - Pillow==9.5.0
        - plotly==5.14.1
        - prettytable==3.7.0
        - protobuf==3.20.3
        - psutil==5.9.4
        - pyarrow==11.0.0
        - pyecharts==2.0.3
        - Pygments==2.15.0
        - Pympler==1.0.1
        - pyparsing==3.0.9
        - pyrsistent==0.19.3
        - python-dateutil==2.8.2
        - pytz==2023.3
        - pytz-deprecation-shim==0.1.0.post0
        - rdt==1.4.0
        - requests==2.28.2
        - rich==13.3.4
        - s3transfer==0.6.0
        - scikit-learn==1.2.2
        - scipy==1.10.1
        - sdmetrics==0.9.3
        - sdv==1.0.0
        - simplejson==3.19.1
        - six==1.16.0
        - smmap==5.0.0
        - soupsieve==2.4
        - streamlit==1.21.0
        - tenacity==8.2.2
        - threadpoolctl==3.1.0
        - toml==0.10.2
        - toolz==0.12.0
        - tornado==6.2
        - tqdm==4.65.0
        - typing_extensions==4.5.0
        - tzlocal==4.3
        - urllib3==1.26.15
        - validators==0.20.0
        - watchdog==3.0.0
        - wcwidth==0.2.6
        - zipp==3.15.0
        - streamlit-ace==0.1.1
        - streamlit-echarts==0.4.0
        - openpyxl==3.1.2
        - attrs==23.1.0
        - pydeck==0.8.1b0
        - et-xmlfile==1.1.0
        - graphviz==0.20.1
        - mdurl==0.1.2
