[tool.poetry]
name = "sdv"
version = "0.1.0"
description = "Synthetic Data Vault"
authors = ["Your Name <you@example.com>"]
license = "Business License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.7.1"
streamlit = "^1.21.0"
streamlit-ace = "^0.1.1"
streamlit-echarts = "^0.4.0"
openpyxl = "^3.1.2"
beautifulsoup4 = "^4.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
