# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:  
    runs-on: ${{ matrix.os }}  
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]   #macos-latest fails because no matching distribution found for nvidia-cublas-cu12==12.1.3.1
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi  
        continue-on-error: false
      #- name: Run Ruff 
      #  run: ruff check --output-format=github .
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
      - name: test if app starts
        run: | #do I need to exit this step?
          cd /synthetic_data_talk
          streamlit run 🔓_Synthetic_Data.py
