# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:  
    runs-on: ${{ matrix.os }}  
    strategy:  
      matrix:
        os: [ubuntu-latest, macos-latest]   #windows-latest
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install .  
          pip install .[dev]   
        continue-on-error: false
      - uses: chartboost/ruff-action@v1 #default ruff action or does it use my pyprject.toml?
        with:
          args: '--fix --config=pyproject.toml' #do I need to add --check?
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
      - name: test if app starts
        run: | #do I need to exit this step?
          cd /synthetic_data_talk
          streamlit run 🔓_Synthetic_Data.py
