[theme]

base="light"

# Primary accent for interactive elements
primaryColor = '#1f449c'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#c1cee4'

# Color used for almost all text
textColor = '#202733'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"


